-- MySQL Script generated by MySQL Workbench
-- Thứ sáu, 25 Tháng 2 Năm 2022 17:02:29 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema health_declaration_form
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema health_declaration_form
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `health_declaration_form` DEFAULT CHARACTER SET utf8 ;
USE `health_declaration_form` ;

-- -----------------------------------------------------
-- Table `health_declaration_form`.`epidemiologicalfactor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_declaration_form`.`epidemiologicalfactor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_declaration_form`.`symptom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_declaration_form`.`symptom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_declaration_form`.`healthdeclarationtype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_declaration_form`.`healthdeclarationtype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_declaration_form`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_declaration_form`.`userinfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_card_number` CHAR(11) NULL,
  `house_number` VARCHAR(256) NULL,
  `ward` VARCHAR(256) NULL,
  `district` VARCHAR(256) NULL,
  `province` VARCHAR(256) NULL,
  `nationality` VARCHAR(256) NULL,
  `sex` VARCHAR(256) NULL,
  `date_of_birth` DATETIME NULL,
  `full_name` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `health_declaration_form`.`resulthealthdeclaration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_declaration_form`.`resulthealthdeclaration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `epidemiological_factors` VARCHAR(256) NULL,
  `symtoms` VARCHAR(256) NULL,
  `is_following` VARCHAR(256) NULL,
  `test_code` VARCHAR(256) NULL,
  `declaration_place` VARCHAR(256) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resulthealthdeclaration_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_resulthealthdeclaration_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `health_declaration_form`.`userinfo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
